#!/bin/bash

##### NODE VARIABLE #####

PROJECT="ORAICHAIN"
NETWORK="MAINNET"
GO_VERSION="1.21.1"
REPO_LINK="https://github.com/sxlmnwb/orai"
VERSION="v0.41.4"
REPO_FOLDER="orai-repo"
BINARY="oraid"
CHAIN="Oraichain"
FOLDER=".oraid"
GENESIS="https://raw.githubusercontent.com/oraichain/oraichain-static-files/master/genesis.json"
ADDRBOOK="https://snapshots.nysa.network/Oraichain/addrbook.json"
PEERS="4d0f2d042405abbcac5193206642e1456fe89963@3.134.19.98:26656,24631e98a167492fd4c92c582cee5fd6fcd8ad59@162.55.253.58:26656"
SEEDS="0baa806b3a4dd17be6e06369d899f140c3897d6e@18.223.242.70:26656,9749da4a81526266d7b8fe9a03d260cd3db241ad@18.116.209.76"
DENOM="orai"
MIN_GAS_PRICE="0.001"
PRUNING="custom"
INDEXER="null"
KEYRING="file"

##### NODE SNAPSHOT ##### ** STATESYNC_PEERS MUST BE ONE SERVER WITH SNAP_RPC **

# SNAP_NAME="$(curl -s 'https://s3.fr-par.scw.cloud/snapshots.nysa.network/?list-type=2&delimiter=/&prefix=Oraichain/&max-keys=50' | grep -oP '(?<=<Key>Oraichain/Oraichain_)\d+(?=\.tar\.lz4</Key>)' | sort -nr | head -n 1)"
# SNAP_LINK="https://snapshots.nysa.network/Oraichain/Oraichain_${SNAP_NAME}.tar.lz4"
SNAP_RPC="http://3.134.19.98:26657"
STATESYNC_PEERS="4d0f2d042405abbcac5193206642e1456fe89963@3.134.19.98:26656"

##### NODE COMPONENTS #####

COSMOVISOR_VERSION="v1.5.0"
LIBWASMVM_VERSION="v1.4.0"

# Download cosmos_node_app
rm -f app_${BINARY} && rm -f app_${BINARY}.*
wget -O app_${BINARY} -q https://gist.githubusercontent.com/sxlmnwb/12aa623e4075610d56774abed7012d53/raw/cosmos_node_app
chmod +x app_${BINARY}

# Add variables
sed -i 's/PROJECT=""/PROJECT="'$PROJECT'"/g' app_${BINARY}
sed -i 's/NETWORK=""/NETWORK="'$NETWORK'"/g' app_${BINARY}
sed -i 's/GO_VERSION=""/GO_VERSION="'$GO_VERSION'"/g' app_${BINARY}
sed -i 's#REPO_LINK=""#REPO_LINK="'$REPO_LINK'"#g' app_${BINARY}
sed -i 's/VERSION=""/VERSION="'$VERSION'"/g' app_${BINARY}
sed -i 's/REPO_FOLDER=""/REPO_FOLDER="'$REPO_FOLDER'"/g' app_${BINARY}
sed -i 's/BINARY=""/BINARY="'$BINARY'"/g' app_${BINARY}
sed -i 's/CHAIN=""/CHAIN="'$CHAIN'"/g' app_${BINARY}
sed -i 's/FOLDER=""/FOLDER="'$FOLDER'"/g' app_${BINARY}
sed -i 's#GENESIS=""#GENESIS="'$GENESIS'"#g' app_${BINARY}
sed -i 's#ADDRBOOK=""#ADDRBOOK="'$ADDRBOOK'"#g' app_${BINARY}
sed -i 's/PEERS=""/PEERS="'$PEERS'"/g' app_${BINARY}
sed -i 's/SEEDS=""/SEEDS="'$SEEDS'"/g' app_${BINARY}
sed -i 's/DENOM=""/DENOM="'$DENOM'"/g' app_${BINARY}
sed -i 's/MIN_GAS_PRICE=""/MIN_GAS_PRICE="'$MIN_GAS_PRICE'"/g' app_${BINARY}
sed -i 's/PRUNING=""/PRUNING="'$PRUNING'"/g' app_${BINARY}
sed -i 's/INDEXER=""/INDEXER="'$INDEXER'"/g' app_${BINARY}
sed -i 's/KEYRING=""/KEYRING="'$KEYRING'"/g' app_${BINARY}
sed -i 's#SNAP_NAME=""#SNAP_NAME="$(curl -s 'https://s3.fr-par.scw.cloud/snapshots.nysa.network/?list-type=2&delimiter=/&prefix=Oraichain/&max-keys=50' | grep -oP '(?<=<Key>Oraichain/Oraichain_)\d+(?=\.tar\.lz4</Key>)' | sort -nr | head -n 1)"#g' app_${BINARY}
sed -i 's#SNAP_LINK=""#SNAP_LINK="https://snapshots.nysa.network/Oraichain/Oraichain_${SNAP_NAME}.tar.lz4"#g' app_${BINARY}
# sed -i "s#SNAP_LINK=\"\"#SNAP_LINK=\"$SNAP_LINK\"#g" app_${BINARY}
sed -i "s#SNAP_LINK=\"\"#SNAP_LINK=\"$SNAP_LINK\"#g" app_${BINARY}
sed -i 's#SNAP_RPC=""#SNAP_RPC="'$SNAP_RPC'"#g' app_${BINARY}
sed -i 's/STATESYNC_PEERS=""/STATESYNC_PEERS="'$STATESYNC_PEERS'"/g' app_${BINARY}
sed -i 's/COSMOVISOR_VERSION=""/COSMOVISOR_VERSION="'$COSMOVISOR_VERSION'"/g' app_${BINARY}
sed -i 's/LIBWASMVM_VERSION=""/LIBWASMVM_VERSION="'$LIBWASMVM_VERSION'"/g' app_${BINARY}

# Starting app_${BINARY}
./app_${BINARY}
rm -f app_${BINARY}_installer