#!/bin/bash

##### NODE VARIABLE #####

PROJECT="SGE"
NETWORK="MAINNET"
GO_VERSION="1.21.1"
REPO_LINK="https://github.com/sge-network/sge.git"
VERSION="v1.1.1"
REPO_FOLDER="sge-repo"
BINARY="sged"
CHAIN="sgenet-1"
FOLDER=".sge"
GENESIS="https://snap.nodex.one/sge/genesis.json"
ADDRBOOK="https://snap.nodex.one/sge/addrbook.json"
PEERS="0e9387a4aa548998eda8f2bb4a5cd799345d5367@sge.rpc.nodex.one:11456"
SEEDS="5f5cfac5c38506fbb4275c19e87c4107ec48808d@seeds.nodex.one:11410"
DENOM="usge"
MIN_GAS_PRICE="0"
PRUNING="custom"
INDEXER="null"
KEYRING="file"

##### NODE SNAPSHOT ##### ** STATESYNC_PEERS MUST BE ONE SERVER WITH SNAP_RPC **

SNAP_NAME=""
SNAP_LINK=""
SNAP_RPC="https://sge.rpc.nodex.one:443"
STATESYNC_PEERS="0e9387a4aa548998eda8f2bb4a5cd799345d5367@sge.rpc.nodex.one:11456"

##### NODE COMPONENTS #####

COSMOVISOR_VERSION="v1.5.0"
LIBWASMVM_VERSION="v1.4.0"

# Download cosmos_node_app
rm -f app_${BINARY} && rm -f app_${BINARY}.*
wget -O app_${BINARY} -q https://gist.githubusercontent.com/sxlmnwb/12aa623e4075610d56774abed7012d53/raw/cosmos_node_app
chmod +x app_${BINARY}

# Add variables
sed -i 's/PROJECT=""/PROJECT="'$PROJECT'"/g' app_${BINARY}
sed -i 's/NETWORK=""/NETWORK="'$NETWORK'"/g' app_${BINARY}
sed -i 's/GO_VERSION=""/GO_VERSION="'$GO_VERSION'"/g' app_${BINARY}
sed -i 's#REPO_LINK=""#REPO_LINK="'$REPO_LINK'"#g' app_${BINARY}
sed -i 's/VERSION=""/VERSION="'$VERSION'"/g' app_${BINARY}
sed -i 's/REPO_FOLDER=""/REPO_FOLDER="'$REPO_FOLDER'"/g' app_${BINARY}
sed -i 's/BINARY=""/BINARY="'$BINARY'"/g' app_${BINARY}
sed -i 's/CHAIN=""/CHAIN="'$CHAIN'"/g' app_${BINARY}
sed -i 's/FOLDER=""/FOLDER="'$FOLDER'"/g' app_${BINARY}
sed -i 's#GENESIS=""#GENESIS="'$GENESIS'"#g' app_${BINARY}
sed -i 's#ADDRBOOK=""#ADDRBOOK="'$ADDRBOOK'"#g' app_${BINARY}
sed -i 's/PEERS=""/PEERS="'$PEERS'"/g' app_${BINARY}
sed -i 's/SEEDS=""/SEEDS="'$SEEDS'"/g' app_${BINARY}
sed -i 's/DENOM=""/DENOM="'$DENOM'"/g' app_${BINARY}
sed -i 's/MIN_GAS_PRICE=""/MIN_GAS_PRICE="'$MIN_GAS_PRICE'"/g' app_${BINARY}
sed -i 's/PRUNING=""/PRUNING="'$PRUNING'"/g' app_${BINARY}
sed -i 's/INDEXER=""/INDEXER="'$INDEXER'"/g' app_${BINARY}
sed -i 's/KEYRING=""/KEYRING="'$KEYRING'"/g' app_${BINARY}
sed -i 's#SNAP_NAME=""#SNAP_NAME="$(curl --max-time 1 -s https://ss.sge.nodestake.top/ | egrep -o ">20.*\.tar.lz4" | tr -d ">")"#g' app_${BINARY}
sed -i 's#SNAP_LINK=""#SNAP_LINK="https://ss.sge.nodestake.top/${SNAP_NAME}"#g' app_${BINARY}
sed -i "s#SNAP_LINK=\"\"#SNAP_LINK=\"$SNAP_LINK\"#g" app_${BINARY}
sed -i 's#SNAP_RPC=""#SNAP_RPC="'$SNAP_RPC'"#g' app_${BINARY}
sed -i 's/STATESYNC_PEERS=""/STATESYNC_PEERS="'$STATESYNC_PEERS'"/g' app_${BINARY}
sed -i 's/COSMOVISOR_VERSION=""/COSMOVISOR_VERSION="'$COSMOVISOR_VERSION'"/g' app_${BINARY}
sed -i 's/LIBWASMVM_VERSION=""/LIBWASMVM_VERSION="'$LIBWASMVM_VERSION'"/g' app_${BINARY}

# Starting app_${BINARY}
./app_${BINARY}
rm -f app_${BINARY}_installer
